### ISSUE TITLE
url_prefix when using blueprints

### ISSUE THREAD

**Issue by NiekKeijzer** [ahopkins/sanic-jwt#104]
I'm trying to initialise SanicJWT on my own blueprint, however it seems to the blueprint appears to be duplicated in this case. First SanicJWT builds the url using the blueprint prefix and once Sanic mounts the blueprint, the prefix is added once again. 

For example this demo app results in the routes below.
```python 
from sanic import Sanic, Blueprint
from sanic_jwt import Initialize

app = Sanic()
bp = Blueprint('bp', url_prefix='/api')
Initialize(
    instance=bp,
    app=app,
    authenticate=lambda: True
)

app.blueprint(bp)
print(app.router.routes_all.keys())

# Result:
dict_keys(['/api/api/auth/', '/api/api/auth', '/api/api/auth/me', '/api/api/auth/me/', '/api/api/auth/verify', '/api/api/auth/verify/', '/api/api/auth/refresh', '/api/api/auth/refresh/'])
```

Unless I'm missing something, I suggest checking if the instance is a user defined blueprint in https://github.com/ahopkins/sanic-jwt/blob/86d6767f961890c51b44409cd91f100e3a96bca9/sanic_jwt/initialization.py#L268

For example something like: 

```python
def _get_url_prefix(self):
    config_url_prefix = self.config.url_prefix
    if self.instance_is_blueprint:
        url_prefix = config_url_prefix
    else:
        bp_url_prefix = self.bp.url_prefix\
        if self.bp.url_prefix is not None else ''
            url_prefix = bp_url_prefix + config_url_prefix
    return url_prefix
```

**Comment by ahopkins** [comment]
Let me know what you see when you remove `app`. I will leave this open for now, but I think this should resolve.

**Comment by vltr** [comment]
@NiekKeijzer do you mind posting just your `Initialization(...)` call?

**Comment by NiekKeijzer** [comment]
Certainly, though in my current test app it's essentially the same as @ahopkins example.

```python 
Initialize(
    bp, 
    authenticate=lambda:True, 
    access_token_name='bp_token')
```

**Comment by ahopkins** [comment]
@NiekKeijzer Sorry for my earlier response. I went back to look at the code and the tests (in particular look at `tests/test_initialize.py` ([Here](https://github.com/ahopkins/sanic-jwt/blob/dev/tests/test_initialize.py#L81) and [here](https://github.com/ahopkins/sanic-jwt/blob/dev/tests/test_initialize.py#L90)).

This is clearly a deficiency in the exception message, and the documentation.

Thinking about this further, your above initialization method was exactly as I had wanted it to be:

```python
Initialize(bp, authenticate=lambda: True)
```

That is simple and easy. The problem is that the `Blueprint` object is not itself aware of the `Sanic` object it is attached to. Therefore, we **DO** need the `app`, and your original initialization **WAS** correct.

======

So, forgive me and let me back up, because I do remember what is going on here now.

![image](https://user-images.githubusercontent.com/166269/39562520-c4a4a4a0-4eb4-11e8-8543-bcbfc183de80.png)

In your first example, you attach the blueprint to the app **after** initialization. This causes this to happen. If you swap the ordering, it will appear as expected:

```python
from sanic import Sanic, Blueprint
from sanic_jwt import Initialize

app = Sanic()
bp = Blueprint('bp', url_prefix='/api')
app.blueprint(bp)

Initialize(
    instance=bp,
    app=app,
    authenticate=lambda: True
)

print('app', app.router.routes_all.keys())
print('bp', [x.uri for x in bp.routes])

# Result:
app dict_keys([])
bp ['/api/auth/', '/api/auth/me', '/api/auth/verify']
```

Is this a bug? Maybe. Unless there is a reason to not have `Initialize` after you register your `Blueprint`. If I remember correctly, this was due to a limitation I came across with Sanic. If there ends up being a good reason that we need to overcome this, I am open to making a change. Otherwise, I see this as staying as is for now (except, perhaps with better docs).
