### ISSUE TITLE
/auth/me status code 200 after token expiration

### ISSUE THREAD

**Issue by Jeffwhen** [ahopkins/sanic-jwt#118]
Request to `/auth/me` is not rejected with `403` after token expiration. Is this intended?

**Comment by ahopkins** [comment]
@Jeffwhen Thanks for pointing this out. I would not call this intended, because it certainly would not be intuitive. However, now that you mention it, I 100% see how this happens. I am going to put together a patch for this and will release it in the next day or two. This is a security risk in my opinion as it allows potentially for data to be leaked unexpectedly. After all, that is the whole point that these tokens expire and become useless.

Thank you very much for your contribution, and if you would like to take a stab at adding the protection feel free to submit a PR.

**Comment by Jeffwhen** [comment]
That method `extract_payload` is throwless. In this case, it only returns `None` after token expiration. The version is `1.1.2`.
