### ISSUE TITLE
Authentication and verify methods hooks to use without routes.

### ISSUE THREAD

**Issue by enf644** [ahopkins/sanic-jwt#173]
Hi, thanks for another great lib!
I can't figure out how to hook up to auth functions without using routes.  I need the authentication process to be available from graphql queries. 

I have a graphql mutation that receives login and password. I want to authenticate the user and return a jwt token. Is there a way to call the /auth method without http request?

Also, I need the same with verify. I am receiving a jwt token throw graphql and i need to verify it. Is there a way to call /auth/verify without http request?

**Comment by ahopkins** [comment]
(1) My apologies for taking way too long to respond.
(2) Thanks for the compliment.
(3) Yes, this should be absolutely possible. I'll post a snippet for you either tonight or tomorrow. I hope this is still relevant.

**Comment by zwjat** [comment]
Where is the snippet of Authentication and verify methods  without routes ?  Thanks

**Comment by ahopkins** [comment]
Sorry, it is on my computer that died. I wrote it and then the machine kicked on me before I could upload it.

Take a look at [this recent commit](https://github.com/ahopkins/sanic-jwt/commit/32e4d8fee2a201098b036899468d76581dfb68a0) that will add methods for inline creation and verification. It is **NOT** released yet because I am waiting for Sanic 19.12 to be released (hopefully with https://github.com/huge-success/sanic/pull/1728). After that, I will fill out the docs and release this.

In the mean time, you can do this exact thing WITHOUT this release.

Take a look at this: https://github.com/ahopkins/sanic-jwt/blob/294636e9dd596ba6fba7a1ef214c77a61a2c7084/sanic_jwt/endpoints.py#L121

Generating a token is pretty easy with this: https://github.com/ahopkins/sanic-jwt/blob/294636e9dd596ba6fba7a1ef214c77a61a2c7084/sanic_jwt/authentication.py#L441

**Comment by ahopkins** [comment]
Let me know if this helps or if you need a more concrete example.
