### ISSUE TITLE
Passing args kwargs from request into is_authenticated method cause unexpected behaviour

### ISSUE THREAD

**Issue by CaptFrozenberg** [ahopkins/sanic-jwt#57]
Hello, I have found a case with unexpected behaviour.

The problem appears when you try to use `protected` decorator with sanic websocket route. 

Test code sample 
```python
@app.websocket('/feed')
@protected()
async def feed(request, ws):
    await ws.send('Hello from protected websocket route')
```

This problem is caused by websocket protocol object which travels in `args` from `is_authenticated` [method](https://github.com/ahopkins/sanic-jwt/blob/master/sanic_jwt/decorators.py#L21) to `verify` [method](https://github.com/ahopkins/sanic-jwt/blob/master/sanic_jwt/authentication.py#L153) and is mistaken for `return_payload` parameter. It has broken my mind when I tried to find a reason for an `Unauthorized` exception which is raised instead of original `ValueError`.

Associated case comes up when you decide to call a parameter in usual sanic route `return_payload` like this

```python
@app.route('/test_jwt/<return_payload>')
@protected()
async def test_jwt(request: Request, return_payload):
    return json({'success': 'ok'})
```
Same situation here. `ValueError` is ovelapped by `Unauthorized` exception.

I see many places where args kwargs are passed but aren't used. I would like to offer removing them from `is_authenticated` method, maybe from other places too. May I try to do a PR for this?

**Comment by CaptFrozenberg** [comment]
Sorry I accidently published uncompleted issue, let me edit it properly

**Comment by ahopkins** [comment]
@CaptFrozenberg Thanks very much for bringing this up. And, while I would love to accept the offer for a PR to clean that up, the `Authentication` class and `initialize` method are [being overhauled](https://github.com/ahopkins/sanic-jwt/commits/initialize). So, I am afraid whatever work you did might not be worth it since there will be a lot of changes (mainly the the configuration and passing of methods at initialize). 

In addition, I am adding some more customizations for returns.

With all of that said, something that I did want to tackle specifically at some point was websocket authentication. It may not be so easy as dropping in the `@protected` decorator. Authentication on the initial HTTP request for websockets has some slightly different concerns, and before I would feel comfortable stating that this package supports Websockets, I think there is some more work to be done. For example, [here is an article on websokcet hijacking](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html).

Perhaps, you could open a new ticket requesting support for Websockets?

**Comment by CaptFrozenberg** [comment]
Thank you for the quick response! I can look into it after you finish making major changes.

About websocket authentication. Thats exactly what I'm currently looking into. In my example app I use sanic-cors package to make restrictions by origin header.
