### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#59]
The `@protected` decorator does not support websockets. We need to explore the possibility of protecting routes like this:

```python
@app.websocket('/feed')
@protected()
async def feed(request, ws):
    await ws.send('Hello from protected websocket route')
```

**Comment by CaptFrozenberg** [comment]
I would be glad to help with implementing this feature

Note for feature documentation: websocket support in browsers allows only Basic or Cookie based authentication

The question has to be resolved. Where to handle websocket hijacking protection? 
There are two variants in my mind. To document the use of third-party cors package or implement needed functionality here.

**Comment by ahopkins** [comment]
I am leaning towards steering the user towards the first: relying upon [`sanic-cors`](https://github.com/ashleysommer/sanic-cors) for now. I do not want to steer this project too far off course and bloat it. The idea being that the documentation would steer the user into how to do it properly. At least in the near term.

If you would like, take a look at #58 with the new `Initialize` class. I hope to merge this into `master` by the end of the month.

**Comment by ahopkins** [comment]
#57

**Comment by vltr** [comment]
@ahopkins I agree on documenting the issue and lead to other implementations, that's not a problem. IMHO, the only problem about websockets is that is does a bit more than just being a full duplex channel, bringing some complexity along. On top of that, its API is _still_ being standardized (for browsers). But, it's usable and [the majority browsers supports them](https://caniuse.com/#search=websocket).

**Comment by CaptFrozenberg** [comment]
Hello, it's me again :) I'm back and digging into websocket support. Recently I have discovered an issue wich has similar reason.

Old one is passing `*args **kwargs` from request handler to is_authenticated method and next to verify method https://github.com/ahopkins/sanic-jwt/blob/dev/sanic_jwt/authentication.py#L225.
For Sanic websocket routes this clashing verify method argument `return_payload` with `ws` arg which sanic passes for websocket routes https://github.com/channelcat/sanic/blob/master/sanic/app.py#L300. 

#57 

And next one is a possibility to always set `verify` argument to `False` (which is very bad) in case you have a route with verify argument defined like this:

```python
@app.route('/my_protected/<verify:int>')
@protected()
async def my_protected(request: Request, verify):
    print(bool(verify))
```
with request path `/my_protected/0/`

Maybe this doesn't look like a serious vulnerability but of course it is not a good thing and should be fixed.
`*args **kwargs` from request mustn't clash with internal params, because of unpredictable result and possible security issues. Currently these params are not used, but if there is a need to keep them for future and extensibility we could avoid bad things by using extra request_args and request_kwargs params and pass them as usual keyword arguments.

I have tested this approach a bit, see https://github.com/ahopkins/sanic-jwt/compare/master...CaptFrozenberg:master. Maybe there are more places where we could use such kind of solution. If this looks ok, I can do a PR, and write a few notes about websockets in docs.

**Comment by ahopkins** [comment]
Makes sense. Please do make a PR, and we will add this.

When you add a PR, do you think you can add a quick test using the route you defined in your example. That certainly would be **very bad** and quite unexpected!

**Comment by CaptFrozenberg** [comment]
OK I'll make tests and a PR as soon as I can

**Comment by ahopkins** [comment]
As far as websockets are concerned, I have used v 1.1 with websockets successfully. As I prepare the docs for release, I'll also include some examples. I'm keeping this open for now, but I think we can close it after the next release.
