### ISSUE TITLE
Add more testing to blueprints

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#63]
Add tests to the following scenarios:

- two different blueprints with their own `sanic_jwt` configuration and check if they do not override one another;
- do the same for both an `app` and a Blueprint.

**Comment by ahopkins** [comment]
The general idea is that as of v1, you and setup `sanic_jwt` on both a `Sanic()` app, or a Sanic `Blueprint()`.

I ran into a little unforseen condition over the weekend. See [Sanic Issue #1132](https://github.com/channelcat/sanic/issues/1132) for some discussion.

In brief, the `request` object contains a reference to the the current running Sanic `app`:

```
async def something(request, *args, **kwargs):
    app = request.app
    ...
```

It does **not** have a reference to the Blueprint. Furthermore, there is no `reverse()` method to track backwards up the stack to get the calling `Route` object (which is a `NamedTuple`). So, while there is access to all of the routes on the `Router` instance (via `request.app.router`), it does not get you there all the way.

Why is this important?

Well, currently, it is needed inside the `@protected` decorator to get the proper `Configuration and Authentication` classes to run.

I have some ideas on how to get around this. But, this is my current hangup since Sanic does not already provide something here to accomplish this.

**Comment by ahopkins** [comment]
[See message here](https://github.com/ahopkins/sanic-jwt/pull/58#issuecomment-367139800). I got around this issue by passing the instance to `@protected`. Not a final resolution, but a working solution for v1.

**Comment by vltr** [comment]
> I got around this issue by passing the instance to @protected. Not a final resolution, but a working solution for v1.

Nice one. Well, given the situation ... I've read the issue on Sanic and, well, this is an acceptable solution IMO.
