### ISSUE TITLE
Getting TypeError: Object of type 'bytes' is not JSON serializable on requests to /auth

### ISSUE THREAD

**Issue by Berkodev** [ahopkins/sanic-jwt#65]
Hi, I'm getting TypeError while trying to authenticate using either my own custom authentication method or this basic method taken from the example:

```
async def authenticate(request):
    return dict(user_id='some_id')
app = Sanic()
initialize(app, authenticate)

...

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=False)
```

I'm making a POST request from a simple tests script like so:
`r = requests.post('http://localhost:8000/auth')`
The client script receives error 500; the server throws this error:
```
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sanic\app.py", line 569, in handle_request
    response = await response
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sanic_jwt\blueprint.py", line 65, in authenticate
    response = get_token_reponse(request, access_token, output, refresh_token)
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sanic_jwt\blueprint.py", line 18, in get_token_reponse
    response = json(output)
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sanic\response.py", line 242, in json
    return HTTPResponse(dumps(body, **kwargs), headers=headers,
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Saar\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

The problem seems to be that the access_token that's generated within the blueprint is being returned as bytes rather than string, so that the Python JSON module is not able to convert the dict to json.

I was able to fix it with some monkey patching, adding the following line at the start of the get_token_reponse (typo here btw) method in blueprint.py:
`output['access_token'] = output['access_token'].decode('ascii')`

If this is indeed a bug, I could probably make a pull request and fix it in a better manner. Thing is, the fact that I seem to be the only one who has this issue makes me think that I may just be doing something wrong.

I'm running the latest version of sanic and sanic_jwt (cloned from the repo) on Python 3.6.1 on Windows.

**Comment by ahopkins** [comment]
Thanks for posting this. First, as for the typo, I believe that was fixed in #58 (PR with a lot of changes, will be merged soon)

As for the bytes string...

I'll take a look when I am back at a machine. I am wondering of it has something to do with Windows. I have not seen this before.

Lastly, I really appreciate the PR offer. I usually would take you up on the offer. But, the package has a lot of changes inside #58 that almost any change you would add would get overwritten at this point. It should be fully backwards compatible, but there are a lot of changes to the internals.

Adam Hopkins

**Comment by vltr** [comment]
@Berkodev this may indeed be a bug. I don't have a Windows box to test this, but I think this is probably the root of this problem since we use [`os.urandom`](https://docs.python.org/3/library/os.html#os.urandom) to generate random strings where needed.

@ahopkins I think that this answers your question [about Windows]

@Berkodev , like @ahopkins said, there's a lot of work under the hood done in #58. I would be asking too much of you to test the #58 PR (the `initialize` branch) on your Windows environment to check if this raises the same error?

**Comment by vltr** [comment]
@Berkodev in fact, where you described, the `output['access_token']` is directly assigned from `jwt.encode(payload, secret, algorithm=algorithm)`, where it may be returning a byte-array in Windows ... I'll have to check that out, no need to test anything in your machine (if you're going to do so) :wink:

@ahopkins I'll have to setup a Windows box to check if this is indeed something a byte-array resulting instead of a string in Windows or if the `json` module in Windows (we don't have `ujson` there) can't handle byte-arrays ...

**Comment by vltr** [comment]
No need even to create a Windows box ...

```python
import json
import jwt
import ujson

x = jwt.encode({'test': 102320}, 'abracadabra', algorithm='HS256')
type(x)
# >>> bytes

json.dumps({'access_token': x})
# >>> TypeError: Object of type 'bytes' is not JSON serializable

ujson.dumps({'access_token': x})
# >>> '{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZXN0IjoxMDIzMjB9.vMI03BrB0hANUeKjpm298Pjpn7p0p80E0URDTeWMjbI"}'
```

What solves is:

```python
x = jwt.encode({'test': 102320}, 'abracadabra', algorithm='HS256').decode('utf-8')

json.dumps({'access_token': x})
# >>> '{"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZXN0IjoxMDIzMjB9.vMI03BrB0hANUeKjpm298Pjpn7p0p80E0URDTeWMjbI"}'

ujson.dumps({'access_token': x})
# >>> '{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZXN0IjoxMDIzMjB9.vMI03BrB0hANUeKjpm298Pjpn7p0p80E0URDTeWMjbI"}'
```

**Comment by Berkodev** [comment]
Hey, just cloned and installed the initialize branch with @vltr's PR #65 on my Windows machine.

Seems to have fixed the issue!

Will report anything else I may come across on Windows.

**Comment by ahopkins** [comment]
@Berkodev and @vltr Nice work on tracking that down. And thanks to you both for being on top of this.

**Comment by sreubenstone99** [comment]
thank you
