### ISSUE TITLE
/auth/me not allowed

### ISSUE THREAD

**Issue by Garito** [ahopkins/sanic-jwt#78]
Hi!
Did you notice that RetrieveUserEndpoint and VerifyEndpoint haven't options defined?
As result the browser raises 405

Could you add them or justify why this is like it is right now?

Thanks!

**Comment by ahopkins** [comment]
Well, I didn't because the thought was that usually it is the nonsafe methods that require preflight requests. I just quickly read through the w3c spec again and referenced [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests), and it I guess my logic was flawed because using certain headers will also trigger a preflight even for a GET. Learn something new every day.

Sorry about that.

I'll push out a fix to add that in later.

**Comment by Garito** [comment]
Nothing to sorry about, this things happend, no worries
Meanwhile I've added this as a workaround:
``` python
@app.options("/auth/me")
def me_options(request):
  return text('', status=204)
```

**Comment by ahopkins** [comment]
[v 1.0.1](https://github.com/ahopkins/sanic-jwt/releases/tag/v1.0.1) Released and published to [pypi](https://pypi.python.org/pypi/sanic-jwt/1.0.1)

**Comment by Garito** [comment]
Works nice
Thanks!
