### ISSUE TITLE
How to pass args or kwargs to extend_payload

### ISSUE THREAD

**Issue by Garito** [ahopkins/sanic-jwt#81]
Or, at least, how to get the request object in that function (as in authenticate or retrieve_user)
Would like to add the user's name & roles for instance (which are in the db accesible in request.app.db ready)

**Comment by ahopkins** [comment]
The easiest way to get at the app instance would be to subclass the authenticator, and extend the payload from there.

```python
from sanic_jwt import Authentication
from sanic_jwt import Initialize


class MyAuthentication(Authentication):
    async def extend_payload(self, payload, *args, **kwargs):
        payload.update({'app_name': self.app.name})
        return payload


app = Sanic('test')
Initialize(
    app,
    authentication_class=MyAuthentication,
)
```

This would yield a payload that looks something like this:

```
{
  "user_id": 1,
  "exp": 1519929852,
  "app_name": "test"
}
```

If you subclass the authenticator, you have access to a bunch of methods inside `extend_payload`, including `self.retrieve_user()`.

**Comment by Garito** [comment]
Nice
Thanks!

**Comment by Garito** [comment]
Hi,
I'm realising that this doesn't solve my question at all (even is good to know that I can pass a class and the advantages it has)

My issue is that I need to access the request object inside the payload if I want to call retrieve_user no matter what way I use the library (methods or class)

Is it possible to pass request to extend_payload?

Thanks

**Comment by ahopkins** [comment]
Hmm, we should probably pass the user object as an argument there.

For now, if you need this functionality, try overwriting `build_payload`. 

```python
async def build_payload(self, user, *args, **kwargs):
    payload = super().build_payload(self, user, *args, **kwargs)
    return payload
```

However, this is a change ripe for a PR of someone wants to help out.

**Comment by ahopkins** [comment]
The other thing too with using `extend_payload` as it currently exists, the `payload` object that gets passed in will contain the `user_id`. Of course if we amend to also pass the user object, it is one less call to your dB, but it could be done without having to override `build_payload`

**Comment by vltr** [comment]
IMO, the `extend_payload` method aims to be simple and not to handle this kind of complexity. Of course, the `request` (and even other objects) could be passed within `kwargs`, so this proposed change will be backwards compatible. But, I think that if your payload aims to be complex, then creating your own `build_payload` method would be more suitable - but, of course, this leaves a hook for the discussion at #70 ...

**Comment by ahopkins** [comment]
@vltr You do raise a good point. Especially since it would not be too difficult to override `build_payload`. However, the point of `extend_payload` is sort of to make it so you do no need to get into `super()`. It essentially is a hook.

Another alternative would be to set `self.user = user` on the `Authentication` class. But, this sort of makes the handler approach irrelevant. I do not particularly like this.

I just pushed a commit that is backwards compatible by using `inspect.getargspec`

```python
extend_payload_args = inspect.getargspec(self.extend_payload)
    if 'user' in extend_payload_args.args:
        ...
```

This way, all of the below work:

```python
def my_extender(payload):
    ...

Initialize(extend_payload=my_extender)
```

```python
def my_extender(payload, user):
    ...

Initialize(extend_payload=my_extender)
```

```python
class MyAuthentication(Authentication):
    async def extend_payload(self, payload, user):
        ...

Initialize(authentication_class=MyAuthentication)
```

I am keeping this on the `dev` branch for now and not committing to `master` because this may be subject to change. So far the tests are fine. But, I still want to think this one through and play around with a few more ideas.

**Comment by Garito** [comment]
Seems good to me (I really don't have any particular opinion on this right now)

**Comment by vltr** [comment]
> Another alternative would be to set `self.user = user` on the `Authentication` class. But, this sort of makes the handler approach irrelevant. I do not particularly like this.

Me neither. In no time `sanic-jwt` will be a framework and not a plugin :sweat_smile: Just kidding ... But we should avoid getting away from some core functionality that exists with `sanic-jwt` since the beginning (like hooks and its simplified nature).

> But, I still want to think this one through and play around with a few more ideas.

Me too. I really like the #70 idea and could help a lot in these kind of edge cases. What do you think?

**Comment by ahopkins** [comment]
I'm closing this and adding it to the slate for v1.1. It makes sense and is an easy convenience.
