### ISSUE TITLE
is_authenticated raises unauthorized

### ISSUE THREAD

**Issue by Garito** [ahopkins/sanic-jwt#86]
Hi!
I've noticed that is_authenticated raises unauthorized instead of returning False
To me, is_authenticated will be useful before check the payload and retrieve the user giving the fact that extract_payload also raises 400 when the call is anonymous

am I correct or misunderstanding something?

**Comment by ahopkins** [comment]
I think this is proper.

> The HTTP 401 Unauthorized client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

[Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)
[RFC 7235](https://tools.ietf.org/html/rfc7235#section-3.1)

Therefore, if there cannot be authentication, a response is due. I don't think there is a need for any further  checks.

Perhaps I misunderstood your question?

**Comment by Garito** [comment]
Perhaps
How you check if there are credentials or not without an exceptions then?

**Comment by ahopkins** [comment]
Do you mean not just whether the token is valid, but that the particular token carries something in the payload to allow access to a particular resource?

For that I would refer you to [scopes](http://sanic-jwt.readthedocs.io/en/latest/pages/scoped.html). It is a flexible system for adding to the payload an additional check against whether a client request carries the proper authentication to reach a resource.

Does this help?

**Comment by ahopkins** [comment]
The main usage of adding to the payload is for the benefit of passing data useful to connect the token to (for example) a user for identification in a client application. The Authentication and Authorization logic is handled by tokens and scopes.

I am of course open to alternative suggestions.

**Comment by Garito** [comment]
No, sorry, doesn't help
I want to check if the request is authenticated or not without raising any exception
How will you do this?

**Comment by vltr** [comment]
Another loose end that could benefit from #70 ....

**Comment by ahopkins** [comment]
Take a [look here](http://sanic-jwt.readthedocs.io/en/latest/pages/endpoints.html#exception-handling). Documentation is not detailed, but the point of this is exactly what you mentioned. catching the exception to be able to redirect to do something else.

**Comment by Garito** [comment]
Sorry @ahopkins  but not everyone likes to try something and catch the exception as you like (same for authenticate and so on). Even instead of and if you need a lot more statements with that way
And besides that, is_authenticated seems to indicate that will be returning True/False not raising an exception so adds confusion
So, don't take it personal, please, but I really don't like the try/catch taste of this library at all, not a single bit

**Comment by ahopkins** [comment]
Point well taken, and no offense received. 😎

As @vltr mentioned, we do want to add some more hooks. And perhaps that term is_ may be confusing.

**Comment by Garito** [comment]
Thanks
I just want to point (and perhaps start a debate or whatever) that exceptions are for RARE conditions not to check states and so on

**Comment by ahopkins** [comment]
Let the debate begin! 

It is an issue I think with a practical application here, but a much bigger design pattern discussion. I'm not sure I agree that try...except... is for rarity only.

In fact, the debate between asking permission/forgiveness is baked into python itself and has been for many years.

> Easier to ask for forgiveness than permission. This common Python coding style assumes the existence of valid keys or attributes and catches exceptions if the assumption proves false. This clean and fast style is characterized by the presence of many try and except statements. The technique contrasts with the LBYL style common to many other languages such as C.

https://docs.python.org/3.6/glossary.html#term-eafp

So I understand is_authenticated may be a misleading term. But I'm not sure I agree that the application should not throw exceptions. The exception is a great way to pull the escape lever and let it trickle down and be known that authentication failed as opposed to carrying that thru is some sort of state.

**Comment by Garito** [comment]
I found that super rought (like if you try to slap me with the excuse of not knowing I don't like that)
And if we take in account how may statements are executed in both methods exceptcions fails like a champ
In this particular example, I could try to get the payload and catch the error (is what already doing) but with only one function call with few checkings in the request I will do with the is_authenticated working properly. How many statements will run the payload retriever till it fails and raises the exception? We could check in this particular case but as a pattern... no way

**Comment by vltr** [comment]
@Garito I was not a fan of using try / exception in Python, too. But I had to read and understand why so many libraries (and particularly libs ([here](https://github.com/requests/requests/blob/master/requests/exceptions.py), [here](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/exc.py), [here](https://github.com/channelcat/sanic/blob/master/sanic/exceptions.py) ...)) adopt these pattern. Basically, the answer (as I understood) is simple: with a good set of exceptions, you can build a better error management flow in your system. A simple `True` or `False` may indicate the final state, but sometimes it is important to know **why**.

I really like the [Python guide](http://docs.python-guide.org/en/latest/) that @kennethreitz put togheter. You can see something about exceptions [here](http://docs.python-guide.org/en/latest/writing/style/#returning-values).

Also, it is better for testing: since you have potential errors mitigated into exceptions, you can track them closely and make sure that a `False` or `None` does not break compatibility elsewhere when a "fail" cause changes the code flow but not the required (or tested) result. A simple example: one required key into the dictionary.

```python
assert my_dict.get('something') is None
assert my_dict['something'] is None

# or ...

assert my_dict.get('something') is None
try:
    assert my_dict['something'] is None
except KeyError:
    print('uh oh ...')
```

This produces different behaviors - and pure Python. Of course, `'something' in my_dict` would test the existence of the key, but that's quite not the point of this example.

As `sanic-jwt` is implemened now, focusing first on being a quick-start using lib, we didn't gave too much focus on these optimizations, but we're working on it and your case does makes a point, since I found this interesting too. That's why I mentioned #70 earlier, to "simplify" the implementation if you want to customize some parts or the whole thing, without having to worry about rewriting bits of code - and, of course, without breaking the "quick-start using library" aspect :wink:

**Comment by Garito** [comment]
Let's separate this in two pieces:
The pattern and is_authenticated

We all are agree that is_authenticated doesn't work as expected (or unfortunated name at least)
I would prefer is_authenticated returns what is expected rather than change name/disapear

The pattern question, thought, is another discussion: any pattern has its place but misplacing it is dangerous and tend to confuse the reader of the code

For instance authenticate, it returns always 401 unauthorized so doesn't make any point to know the reason cause will be a security concern to inform the client of the particular problem (email/name doesn't exist, password failed, ...)

I understand that one tends to fit patterns everywhere to avoid heterogeneous code but a misplaced pattern is two problems: the misplacement will confuse the reader till they realise it is a patternitis issue and the poor solution that the pattern itself introduces (that you call optimization code but for me is making things with common sense)

One thing is optimize a piece of code, another is to try to add 2 numbers by binary aritmetics (for instance) because is a pattern I like and it fits here (by force but fits)

**Comment by vltr** [comment]
@Garito thanks for separating the topics.

- **is_authenticated**: indeed, its name suggests that a `bool` should be returned, perhaps the evolution of the lib itself made this error prone for usage and understanding. We'll work on that.
- **pattern**: as I stated, we're moving towards a more flexible API if one needs to customize - but some messages in `authenticate` can be provided by you directly as it is today. If (these messages) are provided in any other protected method, then we should also work further to make this, at least, usable for everyone (given the effort one wants to spend extending / specializing a [method|object]). We just can't assume everyone will be pleased by any particular pattern, but we need to justify its usage and improve the code (where needed). There is some polishing in the way (as we plan more features), but our intention is always to be developer friendly, not otherwise. For now this may not pleases you, but we're trying to find time here and there to increment this library precisely on other developers needs (not only ours), so stay tuned, there are work to be done :wink:

**Comment by Garito** [comment]
Fair enought
I could say you always try to help me on using this library and very open for our suggestions/issues/needs
So, my support goes for you
Meanwhile, as I probably express already, I have the code that works ok in this current state, so no russ will come from my part
Feel free to close this issue if you prefer or leaved it open in case you use them as marker or whatever

**Comment by vltr** [comment]
@Garito thank you for your support and trust on us and also for using this awesome lib :wink: If you have any ideas or considerations (about implementations) on what you would be the best solution for you, even if a pseudo-code snippet, that would be great :simple_smile: Specially if you already have code that makes that, even if a workaround to suit your needs.

@ahopkins what do you think about? I think it is possible to tackle `is_authenticated` to make it sound more "obvious" and return a `bool` - while more refined checks could be made elsewhere. Also, it would be good to tackle this along #70 (if not obvious). This could also tackles #84 (that I have something done at the office), #81 (also refered by @Garito ) and #71 (which kind of relates with this very issue, doesn't it?). For v1.1, I think we can then focus on #67 (if needed, this road can also be open prior to v1.1), #72 and #68 (which I have made some tests, but not widely usable, _at all_).

**Comment by ahopkins** [comment]
@Garito, I owe you an apology. I absolutely did not mean to offend you, and that my words were received as a slap, I am sorry and hope you forgive me. Honestly, I was excited to hear you explain why your idea was better. As a trained attorney, perhaps I am sometimes too eager to engage in intellectual discussions, rather than the practical one at hand.

Also, I meant not to infer that you were uninformed. Quite the opposite. In fact, from this and other conversations, I gathered that you are a highly capable and knowledgeable developer. However, not everyone reading this may be. And, from my own experience, I often used to (and still sometimes do) feel overwhelmed and self doubting if someone is talking about something I don't know. And therefore, being sensitive to that, I try not to assume too much and instead aim for the lower end to continue to encourage people to get and stay involvednin open source. If you look at my own GitHub history, you will see I was a member and user if open source projects long before I ever decided to make my code available and (more importantly) comment and engage on other projects.

This project began as a need that I had. Then, seemingly there were others that were benefiting from the code so I have been trying to help and make myself and this code available. In most way do I assert that it is the best or only way.

I hope you can accept my apology, and I hope you understand I meant no harm.

As for the rest of the conversation with you and @vltr, it is important to me to have this squared away with first, and later today or tomorrow when I have another chance to sit in front of a computer or will respond again.

Thank you so very much for your willingness to engage and present your ideas and feedback.

**Comment by Garito** [comment]
@ahopkins "au contarire", my friend:
1.- An most important: no offence taken nor sensation of you being rought with me at all (the slap thing was about the exception driven development :))
2.- I do myself like strong opinions and I like to defend my view in a strong way (sometimes too much) too
3.- I am myself, too, too shy with my code which is something I try to solve (eventually :))
4.- When  I said I support you I meant in the sense I really understand what you are saying and how you see what is happening here now in pure enginering terms cause I see myself in you in other time/places
So, thanks a lot to you, now, for taking the time and the humility to ask apologies, not too many people have the balls (allow me to insist: there's no need here for apologies, but thanks)

**Comment by Garito** [comment]
@vltr will post issues if I found something, thanks again
Meanwhile if you need some snippets about what I'm doing with that, my use case is not particular special so could be easy to share, ask for it (I end up in my bubble and don't really know what would be useful for you that I have)

**Comment by vltr** [comment]
Thanks, @Garito ! Any feedback is important, like how you're using `is_authenticated` now and how you're dealing with the exceptions raised, that could perhaps be shrunk to more simple methods that could suit (not only) your case; to improve docs, examples, etc. And don't worry about your bubble, one can get easily lost or found :wink:

**Comment by vltr** [comment]
> Does this make sense?

Yes, it does. Where are you using this snippet, exactly? Inside every "protected" request, to return a JSON body in case of error?

**Comment by Garito** [comment]
It is my "proof of concept"
Given my use case it will end up in a middleware or something like that
Haven't decide yet

**Comment by ahopkins** [comment]
@Garito If you have not seen it yet, take a look at #87 and the proposal to add user injection onto the request object thru use of the decorator.

**Comment by ahopkins** [comment]
Version 1.1 will have some cleanup to the internal API to make some names meant to be "exposed" to the developer as "public" making more sense (`is_authenticated` being one of them. Also: `generate_access_token`, `generate_refresh_token`, and `extract_scopes` are all renamed without breaking backwards compatibility).

And, [as discussed](https://github.com/ahopkins/sanic-jwt/issues/87#issuecomment-392380786), there is a new `@inject_user` decorator.

**Comment by Garito** [comment]
Hi!
Bad timing for me right now but I will check all this asap
Thanks for the help

**Comment by ahopkins** [comment]
I hope to finish the docs this weekend and push out to pypi by Sunday. 

Thank you. From feedback and help from people like you, this project has gone from a hack to fill a gap in my needs, to a pretty decently featured package.

**Comment by Garito** [comment]
Thanks you for doing it so we must not
No rush from me
